### ISSUE TITLE
EventRewardPopup data 갱신

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/NineChronicles.LiveAssets#146]
다른 값은 이미 실제 값과 같지만 BeginDateTime, EndDateTime 값이 이벤트 기간에 맞게 적용되어야 합니다.

**Comment by ipdae** [comment]
- 확인 필요

**Comment by ipdae** [comment]
https://assets.nine-chronicles.com/live-assets/Json/EventRewardPopupData.json 을 사용하는것으로 확인
